### ISSUE TITLE
Wining!!!

### ISSUE THREAD

**Issue by astersx** [ImagicalGamer/SurvivalGamesV3#32]
Hi! Just won a game , and i didnt get $  (i use EconomyApi),  and didnt got message "You win". !!
Anyway i dont need to money reward for game , just message ("You won!"). !!

**Comment by astersx** [comment]
Another glich,  players can quit during combat and then come back to kill others,  i put Combat Logger, 
The plugin who can 100% fix that is Always Spawn,  but i run survival Worlds so i dont use Always_Spawn :D

This is hard to fix,  so take your time,  becouse the game start as soon as someone tp to Arena!
But u can set that a player who appear in arena during the match to be killed xd.

**Comment by ImagicalGamer** [comment]
Ok, I will fix the combat logging issue. You said the game starts as soon as someone enters the arena?

**Comment by astersx** [comment]
I do /mw tp pvp    and then i join game  on world pvp spawn,  not on spawns sg sets.
But im counted as player.
Players wen die,  they press  main menu and then wen they login they are in game at full hp O.O!!!  They can come back from dead!!  Always Spawn fix that,  but i run Survival Worlds!!

**Comment by ImagicalGamer** [comment]
I'm fixing the "dead players" glitch now. ManyWorlds TP's you to the world spawn it over rides the teleportation system in SurvivalGamesV3. Your players sure do like to find and exploit bugs xP.

**Comment by astersx** [comment]
I even set warp here (only for ops),  and im still counted as player if i warp!!

You can test yourself,  not many players found. Main Menu Glich. xd

**Comment by astersx** [comment]
I just saw on sign  minutes ago,  Running,  5/24,  after 5 seconds,  6/24,  after some tIme,  5/24.
Someone already found the bug,  but i guess he got bored trolling!!!

**Comment by ImagicalGamer** [comment]
Anyone who joins the world is counted as a player of the game. I just fixed your issue publishing release now.

**Comment by astersx** [comment]
I dont think remove a "use" will fix,  becouse in my maps if a player die,  he can use Main Menu and he is like no dead,  all Pocketmine have this glich!!

**Comment by astersx** [comment]
I didnt see what code u added!!  Imma trying now :)

**Comment by ImagicalGamer** [comment]
Use this: https://github.com/ImagicalGamer/SurvivalGamesV3/releases/tag/V3.0.3

**Comment by ImagicalGamer** [comment]
It teleports the player to the default world on PlayerLoginEvent

**Comment by ImagicalGamer** [comment]
I did test it and it worked on ImagicalMine, but Genisys isn't full PHP7 and other bugs so idk what's gonna happen there. xP

**Comment by astersx** [comment]
Not working,  i added the code like this
![screenshot_2016-03-16-19-18-54](https://cloud.githubusercontent.com/assets/13157548/13821663/331e78bc-ebab-11e5-85b6-c6aaa730a0d1.png)

**Comment by astersx** [comment]
This is....
![screenshot_2016-03-16-19-20-35](https://cloud.githubusercontent.com/assets/13157548/13821705/5de10e02-ebab-11e5-90bf-ef5cfddf1643.png)

**Comment by astersx** [comment]
If you cant fix for Genisys,  i can resume  Magic TelePortal  plan :),  set spawn with MSpawns and all who relogin will tp in spawn,  inside the teleportal!!

**Comment by ImagicalGamer** [comment]
What error are you getting if any?

**Comment by ImagicalGamer** [comment]
You can use that until I get that fixed.

**Comment by ImagicalGamer** [comment]
@remotevase PlayerLoginEvent isn't working for Genisys any ideas?

**Comment by astersx** [comment]
Im not getting errors, is just that im still in the map after i relogin!!

**Comment by astersx** [comment]
Error: Can't use method return value in write context
File: /surv.phar/src/SurvivalGamesV3/SurvivalGamesV3
Line: 71
Type: E_COMPILE_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
此次出错由插件引起

Code:
[62]         $spawn = $this->getServer()->getDefaultLevel()->getSafeSpawn(); 
[63]         $this->getServer()->getDefaultLevel()->loadChunk($spawn->getFloorX(), $spawn->getFloorZ());
[64]  $player->teleport($spawn,0,0);
[65] 
[66] 
[67] 	}
[68] 
[69]   
[70] public function playerLogin(PlayerLoginEvent $spawn){ 
[71] $spawn = $this->getServer()->getDefaultLevel()->getSafeSpawn(); $this->getServer() = getDefaultLevel()->loadChunk($spawn->getFloorX(), $spawn->getFloorZ()); $spawn->teleport($spawn,0,0);		}
[72] 
[73] 
[74] 
[75] 
[76] 
[77] 	public function onMove(PlayerMoveEvent $event)
[78] 	{
[79] 		$player = $event->getPlayer();
[80] 		$level = $player->getLevel()->getFolderName();
[81] 		if(in_array($level,$this->arenas))

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

**Comment by erkam2002** [comment]
Genisys Crash Dump Wed Mar 16 18:14:33 UTC 2016

Error: Can't use method return value in write context
File: /SG.phar/src/SurvivalGamesV3/SurvivalGamesV3
Line: 69
Type: E_COMPILE_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
此次出错由插件引起

Code:
[60] 	}
[61] 	
[62] 	Public function playerDeath($spawn) {
[63]         $spawn = $this->getServer()->getDefaultLevel()->getSafeSpawn(); 
[64]         $this->getServer()->getDefaultLevel()->loadChunk($spawn->getFloorX(), 
[65]         $spawn->getFloorZ()); $player->teleport($spawn,0,0);
[66] 	}
[67]         public function playerLogin(PlayerLoginEvent $spawn){
[68]         $spawn = $this->getServer()->getDefaultLevel()->getSafeSpawn(); 
[69]         $this->getServer() = getDefaultLevel()->loadChunk($spawn->getFloorX(), 
[70]         $spawn->getFloorZ()); $spawn->teleport($spawn,0,0);
[71] 		}
[72]         
[73] 	public function onMove(PlayerMoveEvent $event)
[74] 	{
[75] 		$player = $event->getPlayer();
[76] 		$level = $player->getLevel()->getFolderName();
[77] 		if(in_array($level,$this->arenas))
[78] 		{
[79] 			$config = new Config($this->getDataFolder() . "/config.yml", Config::YAML);

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

Genisys version: 1.1dev #154 [Protocol 45; API 2.0.0]
uname -a: Linux mc12 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u3 (2016-01-17) x86_64
PHP version: 7.0.3
Zend version: 3.0.0
OS : Linux, linux

Loaded plugins:
加载的插件:
BanItem 2.2 by LDX for API(s) 1.0.0, 2.0.0
SWorldEditor Beta_1.5 by Sergey_Dertan for API(s) 1.8.0
TapToDo 2.2.1 by Falk for API(s) 1.0.0
xyz 1.0.1 by unerds for API(s) 1.0.0
EmptyWorld 1.0.0 by aliuly for API(s) 1.12.0
LaunchPads 1.0.0 by MCPEPIG for API(s) 1.0.0
ManyWorlds 2.0.3 by aliuly for API(s) 2.0.0, 1.13.0
PurePerms 1.3.6 by 64FF00 for API(s) 1.13.0, 2.0.0
iProtector 3.1b by LDX for API(s) 1.9.0, 2.0.0
MSpawns 1.5 by EvolSoft for API(s) 1.11.0
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
ServerAuth 2.13 by EvolSoft for API(s) 1.11.0
AdvancedKits 4.0.1 by luca28pet for API(s) 1.12.0
AntiCheat 1.1-R2 by DarkWav (Darku) for API(s) 1.14.0, 2.0.0
AlwaysSpawn 2.2.2 by Philip Shilling for API(s) 1.12.0

Crash

**Comment by ImagicalGamer** [comment]
Download the latest release.

**Comment by ImagicalGamer** [comment]
Never download the ZIP file and compile it only download from [HERE](http://forums.imagicalmine.net/plugins/survivalgames.68/) or [HERE](https://github.com/ImagicalGamer/SurvivalGamesV3/releases)

**Comment by ImagicalGamer** [comment]
@astersx Preventing the player from leaving and re-joining in the arena would do the same thing as Always Spawn and it would do it to all players.

**Comment by astersx** [comment]
I only apply the codes u add on source file i downloaded first :)

**Comment by ImagicalGamer** [comment]
Download from https://github.com/ImagicalGamer/SurvivalGamesV3/releases <- there.

**Comment by ImagicalGamer** [comment]
And for now if your having the issue with Genisys using mspawns and a portal will work until we can fix genisys issues.

**Comment by astersx** [comment]
Okay :)

**Comment by astersx** [comment]
Just to know, relogin not fixed for genisys righ?  Just add "Relogin Fixed For genisys" so i can kow if is fixed, now i use mspawns+ MagicTeleportal!

**Comment by ImagicalGamer** [comment]
Re-Login is not fixed for genisys yet.
